config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('home/', include('course.urls')),
                  path('users/', include('user.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login_page'),
    path('logout/', views.LogoutView.as_view(), name='logout_page'),
    path('register/', views.RegisterView.as_view(), name='register_page'),
    path('activate/<uidb64>/<token>/', views.active, name='activate'),
    path('send-email/', views.SendingEmail.as_view(), name='send_email'),
    path('teachers/', views.TeacherListView.as_view(), name='teachers_list'),
]

course/models.py
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _



User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.title


# class Teacher(models.Model):
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     image = models.ImageField(upload_to='teachers/', blank=True, null=True)
#     telegram_url = models.URLField(max_length=200, blank=True, null=True, validators=[URLValidator()])
#     instagram_url = models.URLField(max_length=200, blank=True, null=True, validators=[URLValidator()])
#
#     @property
#     def full_name(self):
#         return f'{self.first_name} {self.last_name}'

# def clean(self):
#     if not (self.telegram_url or self.instagram_url):
#         raise ValidationError(_("At least one social media URL should be provided."))
#     if self.telegram_url and not URLValidator()(self.telegram_url):
#         raise ValidationError(_("Invalid Telegram URL."))
#     if self.instagram_url and not URLValidator()(self.instagram_url):
#         raise ValidationError(_("Invalid Instagram URL."))


class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='courses/', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='courses')
    teacher = models.ForeignKey('user.Teacher', on_delete=models.CASCADE, related_name='courses')
    rating = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    @property
    def duration_of_video(self):
        total_duration = sum((video.duration for video in self.videos.all()), timedelta())

        total_seconds = int(total_duration.total_seconds())
        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)

        return f'{hours}h {minutes}m {seconds}s'

    def clean(self):
        if self.rating and (self.rating < 0 or self.rating > 5):
            raise ValidationError(_("Rating must be between 0 and 5."))

    def __str__(self):
        return self.name


class Video(models.Model):
    name = models.CharField(max_length=200)
    course = models.ForeignKey('Course', on_delete=models.CASCADE, related_name='videos')
    duration = models.DurationField()
    file = models.FileField(upload_to='videos/')

    class Meta:
        verbose_name = _("Video")
        verbose_name_plural = _("Videos")

    def __str__(self):
        return f'{self.name} - {self.course.name}'


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    phone_number = models.CharField(max_length=20)
    courses = models.ManyToManyField(Course, related_name='customers')

    class Meta:
        verbose_name = _("Customer")
        verbose_name_plural = _("Customers")

    def __str__(self):
        return self.user.username

    def clean(self):
        if not self.phone_number.isdigit():
            raise ValidationError(_("Phone number should only contain digits."))


class Blog(models.Model):
    title = models.CharField(max_length=200, unique=True)
    content = models.TextField()
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogs')

    class Meta:
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")

    def __str__(self):
        return self.title


class Comment(models.Model):
    class RatingChoices(models.IntegerChoices):
        ONE = 1, _("One")
        TWO = 2, _("Two")
        THREE = 3, _("Three")
        FOUR = 4, _("Four")
        FIVE = 5, _("Five")

    blog = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    rating = models.IntegerField(choices=RatingChoices.choices)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['-created_at']

    def __str__(self):
        return f'Comment by {self.user.username} on {self.blog.title}'

    def clean(self):
        if self.rating:
            if self.rating < 1 or self.rating > 5:
                raise ValidationError(_("Rating must be between 1 and 5."))

user/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from user.menegers import MyUserManager

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=35, null=True, blank=True)
    password = models.CharField(max_length=255)
    birth_of_date = models.DateField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_groups',
        blank=True,
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_permissions',
        blank=True,
    )

    def __str__(self):
        return self.email

class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='teachers/', blank=True, null=True)
    telegram_url = models.URLField(max_length=200, blank=True, null=True)
    instagram_url = models.URLField(max_length=200, blank=True, null=True)

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.full_name

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm

from user.models import User


class RegisterModelForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    # def clean(self):
    #     password = self.data.get('password')
    #     password2 = self.data.get('confirm_password')
    #
    #     if password != password2:
    #         raise forms.ValidationError('Passwords do not match.')
    #
    #     return password

    # def save(self, commit=True):
    #     user = super(RegisterModelForm, self).save(commit=False)
    #     user.set_password(self.data['password'])
    #     user.is_active = True
    #     user.is_staff = True
    #     user.is_superuser = True
    #     if commit:
    #         user.save()
    #     return user


class SendingEmailForm(forms.Form):
    subject = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Subject'})
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Your message'}),
        label='Message'
    )
    recipient_list = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter emails separated by commas'}),
        label='Recipient Emails'
    )

    def clean_recipient_list(self):
        data = self.cleaned_data['recipient_list']
        email_list = [email.strip() for email in data.split(',')]
        for email in email_list:
            if not forms.EmailField().clean(email):
                raise forms.ValidationError(f'Invalid email address: {email}')
        return ','.join(email_list)

user/views.py
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views.generic import FormView, ListView, CreateView

from user.forms import RegisterModelForm, SendingEmailForm
from user.models import User


class LoginView(LoginView):
    template_name = 'user/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('index')

    def get_success_url(self):
        return self.success_url


class LogoutView(LogoutView):
    next_page = 'login_page'


class RegisterView(CreateView):
    form_class = RegisterModelForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def active(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('login_page')
    else:
        return render(request, 'activation_invalid.html')


class SendingEmail(FormView):
    template_name = 'send-email.html'
    form_class = SendingEmailForm

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']
        recipient_list = form.cleaned_data['recipient_list'].split(',')
        send_mail(subject, message, 'your_email@example.com', recipient_list)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('send_email')


class TeacherListView(ListView):
    model = User
    template_name = 'teachers_list.html'
    context_object_name = 'teachers'

    def get_queryset(self):
        return User.objects.filter(is_teacher=True)

user/templates/user/Send-email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Send email</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>
{% if sent %}
    <h2>Email successfully sent👍</h2>
{% else %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Send</button>


    </form>
{% endif %}


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>
</html>

user/templates/user/acc-activate-email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

</body>
</html>

user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>ECOURSES - Online Courses HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'course/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'courses/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'courses/css/style.css' %}" rel="stylesheet">
    <!-- Bootstrap CSS -->


</head>

<body>
<!-- Topbar Start -->
<div class="container-fluid d-none d-lg-block">
    <div class="row align-items-center py-4 px-xl-5">
        <div class="col-lg-3">
            <a href="{% url 'index' %}" class="text-decoration-none">
                <h1 class="m-0"><span class="text-primary">Data</span>Talim</h1>
            </a>
        </div>
        <div class="col-lg-3 text-right">
            <div class="d-inline-flex align-items-center">
                <i class="fa fa-2x fa-map-marker-alt text-primary mr-3"></i>
                <div class="text-left">
                    <h6 class="font-weight-semi-bold mb-1">Our Office</h6>
                    <small>Urganch shahri, Al-Xozarmiy ko'chasi 11-uy</small>
                </div>
            </div>
        </div>
        <div class="col-lg-3 text-right">
            <div class="d-inline-flex align-items-center">
                <i class="fa fa-2x fa-envelope text-primary mr-3"></i>
                <div class="text-left">
                    <h6 class="font-weight-semi-bold mb-1">Email Us</h6>
                    <small>Datetalim@gmail.com</small>
                </div>
            </div>
        </div>
        <div class="col-lg-3 text-right">
            <div class="d-inline-flex align-items-center">
                <i class="fa fa-2x fa-phone text-primary mr-3"></i>
                <div class="text-left">
                    <h6 class="font-weight-semi-bold mb-1">Call Us</h6>
                    <small>+998975281055</small>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div class="container-fluid">
    <div class="row border-top px-xl-5">

        <div class="col-lg-3 d-none d-lg-block">
            <a class="d-flex align-items-center justify-content-between bg-secondary w-100 text-decoration-none"
               data-toggle="collapse" href="#navbar-vertical" style="height: 67px; padding: 0 30px;">
                <h5 class="text-primary m-0"><i class="fa fa-book-open mr-2"></i>Subjects</h5>
                <i class="fa fa-angle-down text-primary"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light"
                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 9;">
                <div class="navbar-nav w-100">

                    {% for category in categories %}
                        <a href="{% url 'category_detail' category.id %}"
                           class="nav-item nav-link">{{ category.title }}</a>
                    {% endfor %}

                </div>
            </nav>
        </div>


        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0"><span class="text-primary">Data</span>Talim</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav py-0">
                        <a href="{% url 'index' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'courses_list' %}" class="nav-item nav-link">Courses</a>
                        <a href="{% url 'teachers_list' %}" class="nav-item nav-link">Teachers</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Blog</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'blog_list' %}" class="dropdown-item">Blog List</a>
                                <a href="" class="dropdown-item">Blog Detail</a>
                            </div>
                        </div>
                        <a href="" class="nav-item nav-link">Contact</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->
<div class="container">
    <!-- Login Form -->
    <div class="bg-secondary rounded p-5">
        <h3 class="text-uppercase mb-4" style="
        letter-spacing: 5px;">Login</h3>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email *</label>
                <input type="text" name="email" class="form-control border-0" id="email">
            </div>
            <div class="form-group">
                <label for="password">Password *</label>
                <input type="password" name="password" class="form-control border-0" id="password">
            </div>
            <div class="d-flex">
                <div class="form-group mb-0 mr-2">
                    <input type="submit" value="Log in"
                           href="{% url 'login_page' %}"
                           class="btn btn-outline-primary py-md-2 px-md-4 font-weight-semi-bold">
                </div>
                {#                <div class="form-group mb-0 mr-2">#}
                {#                    <a href="{% url 'social:begin' 'google-oauth2' %}">#}
                {#                        <input type="button" value="Log in using Google"#}
                {#                               class="btn btn-outline-primary py-md-2 px-md-4 font-weight-semi-bold">#}
                {#                    </a>#}
                {#                </div>#}
                <div class="form-group mb-0 mr-2">
                    <a href="{% url 'register_page' %}">
                        <input type="button" value="I don't have an account"
                               class="btn btn-outline-primary py-md-2 px-md-4 font-weight-semi-bold">
                    </a>
                </div>

            </div>

        </form>
    </div>
</div>

<!-- Footer Start -->
<div class="container-fluid bg-dark text-white py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
    <div class="row pt-5">
        <div class="col-lg-7 col-md-12">
            <div class="row">
                <div class="col-md-6 mb-5">
                    <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Get In Touch</h5>
                    <p><i class="fa fa-map-marker-alt mr-2"></i>Urganch shahri,Al-Xorazmiy ko'chasi 11-uy</p>
                    <p><i class="fa fa-phone-alt mr-2"></i>+998975281055</p>
                    <p><i class="fa fa-envelope mr-2"></i>Datatalim@gmail.com</p>
                    <div class="d-flex justify-content-start mt-4">
                        <a class="btn btn-outline-light btn-square mr-2" href=""><i
                                class="fab fa-telegram"></i></a>
                        <a class="btn btn-outline-light btn-square mr-2" href=""><i
                                class="fab fa-instagram"></i></a>
                        <a class="btn btn-outline-light btn-square mr-2"
                           href="https://linkedin.com/company/najot-talim/mycompany"><i class="fab fa-linkedin"></i></a>
                        <a class="btn btn-outline-light btn-square" href=""><i
                                class="fab fa-youtube"></i></a>
                    </div>
                </div>
                <div class="col-md-6 mb-5">
                    <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Our Courses</h5>
                    <div class="d-flex flex-column justify-content-start">
                        {% for course in courses|slice:":7" %}
                            <a class="text-white mb-2" href="{% url 'course_detail' course.slug %}"><i
                                    class="fa fa-angle-right mr-2"></i>{{ course.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-12 mb-5">
            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Newsletter</h5>
            <p>Rebum labore lorem dolores kasd est, et ipsum amet et at kasd, ipsum sea tempor magna tempor. Accu kasd
                sed ea duo ipsum. Dolor duo eirmod sea justo no lorem est diam</p>
            <div class="w-100">
                <div class="input-group">
                    <input type="text" class="form-control border-light" style="padding: 30px;"
                           placeholder="Your Email Address">
                    <div class="input-group-append">
                        <button class="btn btn-primary px-4">Sign Up</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5"
     style="border-color: rgba(256, 256, 256, .1) !important;">
    <div class="row">
        <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
            <p class="m-0 text-white">&copy; <a href="#">Domain Name</a>. All Rights Reserved. Designed by <a
                    href="https://htmlcodex.com">HTML Codex</a>
            </p>
        </div>
        <div class="col-lg-6 text-center text-md-right">
            <ul class="nav d-inline-flex">
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">Terms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">FAQs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white py-0" href="#">Help</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'courses/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'courses/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'courses/mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'courses/mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'courses/js/main.js' %}"></script>
</body>

</html>